export const APP_TITLE = 'Paraty Rotativo'
export const APP_STORE_NAME = 'paraty-rotativo'
export const PROFILE = 5
export const PARKING_LOT_CODE = 922
export const PARKING_MODE_NORMAL = 'normal'
export const PARKING_MODE_DAILY = 'daily'
export const IRREGULARITY_CLOSED_STATUS = 'Fechado'
export const DATE_TIME_WITHOUT_SECONDS = 'dd/LL/yyyy HH:mm'
export const DATE_TIME = 'dd/LL/yyyy HH:mm:ss'
export const DATE = 'yyyy-LL-dd'
export const DATE_BR = 'dd/LL/yyyy'
export const PARKING_LIMIT = 'HH:mm'
export const PAYMENT_DEBIT = 'debit'
export const PAYMENT_CREDIT = 'credit'
export const PAYMENT_STATUS_SUCCESS = 0
export const PAYMENT_STATUS_DENIED = 1
export const PAYMENT_STATUS_CANCELLED = 2
export const PAYMENT_STATUS_FAILED = 3
export const PAYMENT_STATUS_UNKNOWN = 4
export const REDIRECT_INTERVAL = 30000
